//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumTable
    {
        public int id { get; set; }
        public Nullable<int> Num1 { get; set; }
        public Nullable<int> Num2 { get; set; }
        public Nullable<int> Num3 { get; set; }
        public Nullable<int> Num4 { get; set; }
        public Nullable<int> Num5 { get; set; }
        public Nullable<int> Num6 { get; set; }
        public Nullable<int> NumSP { get; set; }
        public string StartDate { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> Seq { get; set; }
        public Nullable<int> SeqFlag { get; set; }
        public Nullable<int> cFlag { get; set; }
        public string NumTrend { get; set; }
        public Nullable<int> Num { get; set; }
    }
}
